"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$rust\
$golang\
$lua\
$docker_context\
$cmd_duration\
$jobs\
$time\
$character"""

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"

[username]
style_user = "bold sapphire"
style_root = "bold red"
format = "[$user]($style)@"
disabled = false

[hostname]
ssh_only = true
style = "bold sapphire"
format = "[$hostname]($style) "

[directory]
style = "overlay1"
truncation_length = 2
truncate_to_repo = true
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "bold mauve"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold peach"
format = "([$all_status$ahead_behind]($style))"

[nodejs]
style = "bold green"
format = "[$symbol($version )]($style)"

[python]
style = "bold yellow"
format = "[$symbol($version )]($style)"

[rust]
style = "bold peach"
format = "[$symbol($version )]($style)"

[golang]
style = "bold sapphire"
format = "[$symbol($version )]($style)"

[lua]
style = "bold blue"
format = "[$symbol($version )]($style)"

[docker_context]
style = "bold blue"
format = "[$symbol$context]($style) "
only_with_files = true

[cmd_duration]
min_time = 2000
style = "bold yellow"
format = "took [$duration]($style) "

[jobs]
symbol = "✦"
style = "bold green"
number_threshold = 1
format = "[$symbol]($style) "

[time]
disabled = false
style = "bold pink"
format = "[$time]($style)"
time_format = "%H:%M"

[character]
disabled = true
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
