# basic configuration
backend = "glx";
vsync = true;

unredir-if-possible = true;
glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;

# transparancy settings for i3
opacity-rule = [
    "100:name *= 'YouTube'"
];

active-opacity = 0.96;
inactive-opacity = 0.90;
frame-opacity = 1.0;

blur:
{
    method = "gaussian";
    size = 10;
    deviation = 25.0;
};
corner-radius: 15;
shadow:
{
    radius:10;
    opacity:70;
};
